### PR TITLE
Add WriteDeadline

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
TestTinyReadBuffer test hangs (atleast on Windows), yet I don't understand why.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Comments?

**Comment by xtaci** [comment]
Strange, i'm trying to figure out why.

**Comment by xtaci** [comment]
Yes, I know why.

You cannot just return the num of bytes written by s.conn.Write to the caller.

You have to sub the header size.

**Comment by xtaci** [comment]
a564c0fd-fb41-4fe7-9f79-c90879b94fd2

**Comment by AudriusButkevicius** [comment]
Thanks, fixed.

Let me know if there is anything else you want addressed.

Also, what would be your appetite to adding:
```
        LocalAddr() Addr
        RemoteAddr() Addr
```
to satisfy net.Conn?

I know this works for generic streams, yet I'd be surprised if anyone uses it outside of the networking context.

**Comment by xtaci** [comment]
1. you cannot just simply ```n:   n - headerSize```, what if n is smaller than headerSize?

2.         
```
LocalAddr() Addr
RemoteAddr() Addr
```
i think just return nil would be ok, because streams are not addressable.

**Comment by AudriusButkevicius** [comment]
Addressed.

**Comment by xtaci** [comment]
looks good to me.

**Pull request merged**
